### ISSUE TITLE
GUI is non-scaling

### ISSUE THREAD

**Issue by haasnhoff** [haasnhoff/mpvconfigurator#2]
The GUI is currently not scaling with the window which is extremely problematic for people with 1280x720 screens or similar resolutions. Currently it is stuck at 1000x900, but it should be dynamic.

Solving this requires a rewrite of the GUI and will be a pain, but it needs to be done.

**Comment by Shou** [comment]
for a quick solution you could hack in a makeshift scrollbar or vertical window resizing so it's possible to reach all options, and then work on the better UI that'll take more time

**Comment by haasnhoff** [comment]
I think instead of going around the issue temporarily, it's better to just destroy it at the root cause which is not using forms but pixel point elements. I'll start fixing it right away since it seems to be the biggest bug right now.

**Comment by haasnhoff** [comment]
Completed. Build will be up soon.
